
import { Frame, ThemeConfig, Language } from './types';

const toSafeBase64 = (str: string) => {
  try {
    return btoa(unescape(encodeURIComponent(str)));
  } catch (e) {
    console.error("Base64 encoding failed", e);
    return "";
  }
};

export const TRANSLATIONS = {
  vi: {
    adminTitle: "Bảng Điều Khiển",
    totalPhotos: "Tổng số ảnh đã chụp",
    branding: "Thương Hiệu",
    frames: "Khung Ảnh",
    devices: "Thiết Bị",
    storage: "Lưu Trữ Cloud",
    eventInfo: "Thông tin sự kiện",
    eventTitle: "Tên Tiệm Ảnh",
    eventSubtitle: "Lời chào / Hướng dẫn",
    captureButtonLabel: "Nút Chụp",
    uploadButtonLabel: "Nút Tải Ảnh",
    primaryColor: "Màu nhấn (Nút bấm)",
    bgColor: "Màu nền ứng dụng",
    frameList: "Danh sách khung",
    addPngFrame: "Thêm Khung PNG",
    aiGenTitle: "Sáng tạo khung bằng AI",
    aiGenDesc: "Mô tả ý tưởng của bạn, AI sẽ tự tạo khung ảnh duy nhất.",
    aiGenPlaceholder: "Nhập ý tưởng khung ảnh...",
    aiGenButton: "Tạo Ngay",
    remixMagic: "Biến hóa AI",
    doodle: "Vẽ tay",
    decor: "Trang trí",
    filters: "Màu sắc",
    scale: "Tỉ lệ",
    undo: "Hoàn tác",
    delete: "Xóa",
    aiRemixBeauty: "Làm Đẹp",
    aiRemixCyber: "Cyber",
    aiRemixMascot: "Đứng cùng Aiyogu",
    aiRemixAnime: "Anime",
    aiRemixWait: "Đang triệu hồi Aiyogu...",
    aiRemixDesc: "Đang nhờ Aiyogu chạy đến đứng cùng bạn, chờ xíu nhé!",
    aiRemixError: "AI remix thất bại!",
    close: "Đóng",
    ready: "Sẵn sàng chưa?",
    smile: "Cười lên nào!",
    badges: "Thông tin bổ sung (Badges)",
    addBadge: "Thêm Badge",
    topText: "Dòng trên",
    bottomText: "Dòng dưới",
    iconType: "Loại Icon",
    logoSettings: "Cài đặt Logo",
    uploadLogo: "Tải Logo lên",
    removeLogo: "Xóa Logo",
    loadingIconSettings: "Cài đặt Icon Loading",
    uploadLoadingIcon: "Tải Icon Loading",
    removeLoadingIcon: "Xóa Icon",
    backgroundSettings: "Cài đặt Hình nền",
    uploadBackground: "Tải Hình nền lên",
    removeBackground: "Xóa Hình nền",
    homeLabels: "Nhãn màn hình chính",
    resultLabels: "Nhãn màn hình kết quả",
    topBadgeLabel: "Badge tiêu đề nhỏ",
    mascotLabel: "Text trong khung Mascot",
    congratsLabel: "Tiêu đề chúc mừng",
    instrLabel: "Hướng dẫn quét QR",
    qrLabel: "Text mã QR",
    downloadBtnLabel: "Nút Tải ảnh",
    retakeBtnLabel: "Nút Chụp lại",
    cameraSettings: "Cài đặt Camera",
    selectCamera: "Chọn thiết bị quay",
    defaultCamera: "Camera mặc định (Tự động)",
    refreshDevices: "Làm mới danh sách",
    noCameraFound: "Không tìm thấy camera nào.",
    original: "Gốc",
    beauty: "Làm đẹp",
    neon: "Neon",
    vivid: "Vực rỡ",
    bw: "Trắng đen",
    save: "Lưu ảnh",
    firebaseSettings: "Cài đặt Firebase Storage",
    firebaseHint: "Đã kết nối với Firebase. Ảnh sẽ tự động được tải lên Cloud và tạo mã QR.",
    saveConfig: "LƯU",
    saveConfigSuccess: "Đã lưu thành công!",
    saveConfigError: "Lỗi khi lưu!",
    saving: "Đang lưu...",
    typography: "Cỡ chữ (Typography)",
    titleSize: "Tiêu đề chính",
    subtitleSize: "Slogan / Phụ đề",
    buttonSize: "Chữ nút bấm",
    badgeSize: "Chữ Badge nhỏ",
    resultTitleSize: "Tiêu đề kết quả",
    loadingTextSize: "Chữ màn hình chờ",
    resultSubtitleSize: "Hướng dẫn kết quả",
    qrTitleSize: "Tiêu đề QR",
    qrSubtitleSize: "Mô tả QR"
  },
  en: {
    adminTitle: "Admin Console",
    totalPhotos: "Total photos taken",
    branding: "Branding",
    frames: "Frames",
    devices: "Devices",
    storage: "Cloud Storage",
    eventInfo: "Event Information",
    eventTitle: "Booth Name",
    eventSubtitle: "Welcome / Instructions",
    captureButtonLabel: "Capture Button",
    uploadButtonLabel: "Upload Button",
    primaryColor: "Primary Color",
    bgColor: "Background Color",
    frameList: "Frame List",
    addPngFrame: "Add PNG Frame",
    aiGenTitle: "AI Frame Generator",
    aiGenDesc: "Describe your idea, AI will create a unique frame.",
    aiGenPlaceholder: "Enter frame idea...",
    aiGenButton: "Generate Now",
    remixMagic: "AI Magic",
    doodle: "Doodle",
    decor: "Decor",
    filters: "Filters",
    scale: "Scale",
    undo: "Undo",
    delete: "Delete",
    aiRemixBeauty: "Retouch",
    aiRemixCyber: "Cyber",
    aiRemixMascot: "Stand with Aiyogu",
    aiRemixAnime: "Anime",
    aiRemixWait: "Aiyogu is coming...",
    aiRemixDesc: "Summoning Aiyogu to stand with you!",
    aiRemixError: "AI remix failed!",
    close: "Close",
    ready: "Are you ready?",
    smile: "Say Cheese!",
    badges: "Info Badges",
    addBadge: "Add Badge",
    topText: "Top Text",
    bottomText: "Bottom Text",
    iconType: "Icon Type",
    logoSettings: "Logo Settings",
    uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo",
    loadingIconSettings: "Loading Icon Settings",
    uploadLoadingIcon: "Upload Loading Icon",
    removeLoadingIcon: "Remove Icon",
    backgroundSettings: "Background Settings",
    uploadBackground: "Upload Background",
    removeBackground: "Remove Background",
    homeLabels: "Home Screen Labels",
    resultLabels: "Result Screen Labels",
    topBadgeLabel: "Top Badge Label",
    mascotLabel: "Mascot Box Text",
    congratsLabel: "Congrats Title",
    instrLabel: "QR Instructions",
    qrLabel: "QR Label",
    downloadBtnLabel: "Download Button",
    retakeBtnLabel: "Retake Button",
    cameraSettings: "Camera Settings",
    selectCamera: "Select Input Device",
    defaultCamera: "Default Camera (Auto)",
    refreshDevices: "Refresh List",
    noCameraFound: "No cameras found.",
    original: "Original",
    beauty: "Beauty",
    neon: "Neon",
    vivid: "Vivid",
    bw: "B&W",
    save: "Save",
    firebaseSettings: "Firebase Storage Settings",
    firebaseHint: "Connected to Firebase. Photos will be auto-uploaded to Cloud for QR generation.",
    saveConfig: "SAVE",
    saveConfigSuccess: "Saved Successfully!",
    saveConfigError: "Save Failed!",
    saving: "Saving...",
    typography: "Typography Sizes",
    titleSize: "Main Title",
    subtitleSize: "Subtitle / Slogan",
    buttonSize: "Button Text",
    badgeSize: "Small Badge",
    resultTitleSize: "Result Title",
    loadingTextSize: "Loading Screen Text",
    resultSubtitleSize: "Result Instructions",
    qrTitleSize: "QR Title",
    qrSubtitleSize: "QR Description"
  }
};

export const INITIAL_FRAMES: Frame[] = [
  {
    id: 'default-45',
    name: 'Aiyogu Portrait',
    url: `data:image/svg+xml;base64,${toSafeBase64(`
      <svg width="1080" height="1350" viewBox="0 0 1080 1350" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="30" y="30" width="1020" height="1290" rx="60" stroke="#10b981" stroke-width="20" stroke-opacity="0.3"/>
        <rect x="0" y="1220" width="1080" height="130" fill="#050a09"/>
        <text x="60" y="1300" font-family="Arial" font-weight="900" font-size="50" fill="#10b981">AI YOUNG GURU</text>
        <circle cx="1000" cy="1285" r="15" fill="#f59e0b" />
        <path d="M900 1285 L950 1285" stroke="#ffffff" stroke-width="2" stroke-opacity="0.2" />
      </svg>
    `)}`,
    isAiGenerated: false,
  }
];

export const DEFAULT_THEME: ThemeConfig = {
  eventTitle: "AI YOUNG GURU",
  eventSubtitle: "Chụp ảnh cùng Mascot thông minh nhất!",
  logoUrl: "",
  loadingIconUrl: "", // Default empty
  backgroundImageUrl: "",
  primaryColor: "#10b981", 
  backgroundColor: "transparent",
  fontFamily: "'Be Vietnam Pro', sans-serif",
  
  fontSizes: {
    title: 60,
    subtitle: 24,
    badge: 16,
    button: 18,
    resultTitle: 48,
    resultSubtitle: 20,
    loadingText: 30,
    qrTitle: 32,
    qrSubtitle: 16
  },
  
  topBadgeText: "PHOTOBOOTH 4:5",
  shootWithMascotText: "",
  captureButtonText: "CHỤP ẢNH NGAY",
  uploadButtonText: "",
  
  congratsText: "Xinh xỉu luôn! ✨",
  resultInstructions: "Quét mã để tải ảnh 4:5 chất lượng cao",
  downloadButtonText: "TẢI ẢNH",
  retakeButtonText: "Chụp lại",
  qrScanText: "MÃ TẢI ẢNH",

  firebaseConfig: {
    apiKey: "AIzaSyBtlipaQk6A3LyqeGR10piSebV9QOw0Mmw",
    authDomain: "photoboothaiguru.firebaseapp.com",
    projectId: "photoboothaiguru",
    storageBucket: "photoboothaiguru.firebasestorage.app",
    messagingSenderId: "106708359580",
    appId: "1:106708359580:web:f185c00a5937e9eda19059",
    measurementId: "G-HQN68JFK15"
  },

  infoBadges: []
};

export const STORAGE_KEYS = {
  FRAMES: 'aiyoungguru_frames_v5',
  STATS: 'aiyoungguru_stats_v5',
  THEME: 'aiyoungguru_theme_v5',
  LANG: 'aiyoungguru_lang_v5',
};
